### ISSUE TITLE
Error: unknown eBPF opcode 0xc5 (insn #32)

### ISSUE THREAD

**Issue by aalemayhu** [badboy/ebpf-disasm#3]
On newer kernel fails with below error. Do you have a fix for this? Attached object file. Thanks.

```
docker run -v ${PWD}:/tmp scanf/ebpf-disasm -s from-overlay /tmp/bpf_overlay.o    
thread 'main' panicked at '[Disassembler] Error: unknown eBPF opcode 0xc5 (insn #32)', /root/.cargo/git/checkouts/rbpf-44f97f5da1828c73/f1e69a8/src/disassembler.rs:286
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

[bpf_overlay.zip](https://github.com/badboy/ebpf-disasm/files/1472050/bpf_overlay.zip)

**Comment by qmonnet** [comment]
Pretty sure this has to do with the new (added in August) “lower than” or “lower or equal” conditional jumps added to eBPF (see [kernel commit](https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=078295fb9af507abce4976c6e9ff56a67da4e9a0) or [update of the simplified instruction code list](https://github.com/iovisor/bpf-docs/commit/a5376f1a76b45310b7a5bae3c2752204829c2e3f#diff-948223913d341a04f2178d6aa3d286e8)). ebpf-disasm probably does not support them yet?

**Comment by qmonnet** [comment]
Ah, but ebpf-disasm relies if fact on rbpf (my own crate), so I'm the one to blame I suppose. I updated the crate a few days ago, @scanf could you try with the [GitHub version](https://github.com/qmonnet/rbpf) of rbpf? The one from crates.io is certainly not up-to-date.

**Comment by aalemayhu** [comment]
Was thinking something had to be applied here and I would then rebase to get latest changes. Was simpler, just reran cargo and it pulled in your recent changes. Works as expected now. Thanks a lot.

**Comment by qmonnet** [comment]
Great! You're welcome :)
